project:
  type: website

website:
  title: "VatlongosWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Hom
      - about.qmd
      - href: grammar.qmd
        text: Gramma
        
  sidebar:
    - title: "Gramma"
      style: "docked"
      background: light
      contents:
        - href: phonology.qmd
          text: Ol saon mo speling

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

