project:
  type: website
  output-dir: docs

website:
  site-url: https://eleanorlisande.github.io/VatlongosWebsite/
  title: "Vatlongos Websaet"
  page-footer: 
    left: "Copyright 2024, Eleanor Ridge"
  navbar:
    background: primary
    search: true
    left:
      - href: about.qmd
      - href: grammar.qmd
      - href: stories.qmd
        
  sidebar:
    - style: "docked"
      background: light
      contents:
        - grammar.qmd
        - href: phonology.qmd
          
    - style: "docked"
      background: light
      contents:
        - index.qmd
        - href: grammar.qmd
        
        
    - style: "docked"
      background: light
      contents:
        - about.qmd
    
    - style: "docked"
      background: light
      contents:
        - stories.qmd
        - href: 20141027a_n01m001.qmd
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

babelquarto:
  languagecodes:
  - name: bi
    text: "Vesen long Bislama"
  - name: en
    text: "Version in English"
  mainlanguage: 'bi'
  languages: ['en']
title-en: Vatlongos website
lang: bi

