project:
  type: website
  output-dir: docs

website:
  site-url: https://eleanorlisande.github.io/VatlongosWebsite/
  title: "Vatlongos Websaet"
  page-footer: 
    left: "Copyright 2024, Eleanor Ridge"
  navbar:
    background: primary
    search: true
    left:
      - href: about.qmd
      - href: grammar.qmd
      - href: stories.qmd
        
  sidebar:
    - title: "Gramma" 
      style: "docked"
      background: light
      contents:
        - grammar.qmd
        - phonology.qmd
    
    - title: "Grammar" 
      style: "docked"
      background: light
      contents:
        - grammar.en.qmd
        - phonology.en.qmd
    
    - title: "Ol Stori"
      style: "docked"
      background: light
      contents:
        - stories.qmd
        - section: "Lan blo rid"
          contents:
            - primer.qmd
        - section: "Stori blong ol animol"
          contents: 
            - story20141027a.qmd
    
    - title: "Stories"
      style: "docked"
      background: light
      contents:
        - stories.en.qmd
        - section: "Learn to read"
          contents:
            - primer.en.qmd
        - section: "Animal stories"
          contents: 
            - story20141027a.en.qmd
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
 
editor: visual

babelquarto:
  languagecodes:
  - name: bi
    text: "Vesen long Bislama"
  - name: en
    text: "Version in English"
  mainlanguage: 'bi'
  languages: ['en']
title-en: Vatlongos website
lang: bi

