project:
  type: website
  output-dir: docs

website:
  title: "Vatlongos Websaet"
  page-footer: 
    left: "Copyright 2024, Eleanor Ridge"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Hom"
      - href: about.qmd
        text: "Abaot"
      - href: grammar.qmd
        text: "Gramma"
        
  sidebar:
    - title: "Gramma"
      style: "docked"
      background: light
      contents:
        - grammar.qmd
        - href: phonology.qmd
          text: Saon mo speling
          
    - title: "Hom"
      style: "docked"
      background: light
      contents:
        - index.qmd
        
        
    - title: "Abaot"
      style: "docked"
      background: light
      contents:
        - about.qmd
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

