---
title: "Saon mo speling"
---

Japta ia bae i tokabaot ol saon blo Vatlongos, mo sam tingting lo saed blo hao blo raetem ol saon blo Vatlongos.

Japta ia bae i gat fulap toktok we i aot lo eria blo linguistics we oli talemaot 'phonology'. Bae mi traem yusum Bislama we i posibol, be samtaem bae mi mas yusum sam toktok blo Inglis mo linguistics, mo bae mi traem explenem gud.

Tufala toktok we oli impoten blo toktok lo saon hemi consonant mo vowel. Ol consonants oli ol saon we yu blokem air lo maot blo yu. Mo ol vowels oli ol saon we ea i jas kamaot nomo -- yu stap jenisem sep blo hem witem maot mo tang blo yu, be yu no blokem hem.

Tu bae yumi yusum wan special alphabet we ol linguist i talemaot 'International Phonetic Alphabet' (IPA). Sipos yu save ol symbol ia, bae yu andastandem gud ol saon blo evri lanwis lo wol. Taem we mi raetem wan leta insaed lo ol /slash/ o \[skwea bracket\], hemi minim se hemi wan IPA symbol.

Bae yumi tokbaoat ol consonant festaem, afta ol vowel, mo soemaot from wanem oli ol difdifren saon lo Vatlongos. Neks bae yumi tokabaot ol saon blo Bislama mo Inglis we i save kam insaed lo Vatlongos, mo laswan bae yumi tokabaot hao ol saon i save kam tugeta insaed lo ol syllable, we hemi olsem wan bit insaed lo lanwis.

# Ol konsonant

Vatlongos hemi gat 15 saon we oli ol konsonant.

Konsonant hemi gat wan mining lo linguistik we i minim ol saon we yu blokem o ristriktem ol ea flo we i kamaot lo maot blo yu.

I gat ol difren kaen consonant we yumi mekem wetem difren stael, mo lo difren ples blo maot.

## Ol stop

Bae yumi stat wetem /p/ /t/ /k/ from trifala ia yumi mekem lo sem fasin nomo: yumi stopem ea wantaem, afta yumi lego air bakagen mo taem we yumi lego air bakagen, i mekem wan bigfala saon wantaem.

Traem talem /p/ be putum han blo yu lo fored blo fes blo yu. Bae yu harem se i no gat ea, afta bigfala air i kamaot wantaem nomo. Lo English mifala talem se ol saon ia \'stop consonants\'.

Tri saon ia i difren nomo lo ples lo maot we yumi stopem air olsem. /p/ yumi stopem air lo tufala lips blo yumi. /t/ yu stapem air lo fored lo tang. Mo /k/ yu stapem air lo bak blo tang blo yu, antap lo ruf blo maot blo yu.

Traem mekem trifala naoia mo harem se lips mo tang blo yu i stap wea taem we yu mekem.
